### ISSUE TITLE
--image cli argument

### ISSUE THREAD

**Issue by gdamjan** [gdamjan/fb-ask-pass-rs#2]
`--image xyz.bmp` could be used instead of showing the firmware image.

Pros:
- will work with machines that don't support acpi 5.0 bgrt

Cons:
- will have to add support for .jpg .png .gif and .bmp
- more space for the logo on the initramfs
- will have to add --xoffset and --yoffset too

**Comment by vladan** [comment]
This was resolved in #8.

**Comment by gdamjan** [comment]
let's not support  .jpg .png or .gif

no need for --xoffset and --yoffset, the bmp will be centered.

good job
